Attribute VB_Name = "LREncrypt"
Public Function Encode(vText As String)
    Dim i As Integer
    Dim lrLen As Integer
    Dim lrChr As String
    Dim lrFin As String
    
    lrLen = Len(vText)


    Do While i <= lrLen


        DoEvents
            i = i + 1
            lrChr = Mid(vText, i, 1)


            Select Case lrChr
                
                Case "a"
                lrChr = "coe"
                Case "b"
                lrChr = "wer"
                Case "c"
                lrChr = "ibq"
                Case "d"
                lrChr = "am7"
                Case "e"
                lrChr = "pm1"
                Case "f"
                lrChr = "mop"
                Case "g"
                lrChr = "9v4"
                Case "h"
                lrChr = "qu6"
                Case "i"
                lrChr = "zxc"
                Case "j"
                lrChr = "4mp"
                Case "k"
                lrChr = "f88"
                Case "l"
                lrChr = "qe2"
                Case "m"
                lrChr = "vbn"
                Case "n"
                lrChr = "qwt"
                Case "o"
                lrChr = "pl5"
                Case "p"
                lrChr = "13s"
                Case "q"
                lrChr = "c%l"
                Case "r"
                lrChr = "w$w"
                Case "s"
                lrChr = "6a@"
                Case "t"
                lrChr = "!2&"
                Case "u"
                lrChr = "(=c"
                Case "v"
                lrChr = "wvf"
                Case "w"
                lrChr = "dp0"
                Case "x"
                vlrChr = "w$-"
                Case "y"
                lrChr = "vn&"
                Case "z"
                lrChr = "c*4"
                
                
                Case "1"
                lrChr = "aq@"
                Case "2"
                lrChr = "902"
                Case "3"
                lrChr = "2.&"
                Case "4"
                lrChr = "/w!"
                Case "5"
                lrChr = "|pq"
                Case "6"
                lrChr = "ml|"
                Case "7"
                lrChr = "t'?"
                Case "8"
                lrChr = ">^s"
                Case "9"
                lrChr = "<s^"
                Case "0"
                lrChr = ";&c"
                
                
                Case "A"
                lrChr = "$)c"
                Case "B"
                lrChr = "-gt"
                Case "C"
                lrChr = "|p*"
                Case "D"
                lrChr = "1" & Chr(34) & "r"
                Case "E"
                lrChr = "c>:"
                Case "F"
                lrChr = "@+x"
                Case "G"
                lrChr = "v^a"
                Case "H"
                lrChr = "]eE"
                Case "I"
                lrChr = "aP0"
                Case "J"
                lrChr = "{=1"
                Case "K"
                lrChr = "cWv"
                Case "L"
                lrChr = "cDc"
                Case "M"
                lrChr = "*,!"
                Case "N"
                lrChr = "fW" & Chr(34)
                Case "O"
                lrChr = ".?T"
                Case "P"
                lrChr = "%<8"
                Case "Q"
                lrChr = "@:a"
                Case "R"
                lrChr = "&c$"
                Case "S"
                lrChr = "WnY"
                Case "T"
                lrChr = "{Sh"
                Case "U"
                lrChr = "_%M"
                Case "V"
                lrChr = "}'$"
                Case "W"
                lrChr = "QlU"
                Case "X"
                lrChr = "Im^"
                Case "Y"
                lrChr = "l|P"
                Case "Z"
                lrChr = ".>#"
                
                Case "!"
                lrChr = "\" & Chr(34) & "]"
                Case "@"
                lrChr = "cY,"
                Case "#"
                lrChr = "x%B"
                Case "$"
                lrChr = "a*v"
                Case "%"
                lrChr = "'&T"
                Case "^"
                lrChr = ";%R"
                Case "&"
                lrChr = "eG_"
                Case "*"
                lrChr = "Z/e"
                Case "("
                lrChr = "rG\"
                Case ")"
                lrChr = "]*F"
                Case "_"
                lrChr = "@B*"
                Case "-"
                lrChr = "+Hc"
                Case "="
                lrChr = "&|D"
                Case "+"
                lrChr = "(:#"
                Case "["
                lrChr = "SlW"
                Case "]"
                lrChr = "'QB"
                Case "{"
                lrChr = "{D>"
                Case "}"
                lrChr = "+c%"
                Case ":"
                lrChr = "(s:"
                Case ";"
                lrChr = "^a("
                Case "'"
                lrChr = "16."
                Case Chr(34)
                lrChr = "s.*"
                Case ","
                lrChr = "&?W"
                Case "."
                lrChr = "GPQ"
                Case "<"
                lrChr = "SK*"
                Case ">"
                lrChr = "RL^"
                Case "/"
                lrChr = "40C"
                Case "?"
                lrChr = "?#9"
                Case "\"
                lrChr = "_?/"
                Case "|"
                lrChr = "(_@"
                Case " "
                lrChr = "=#B"
            End Select
        lrFin = lrFin & lrChr


        DoEvents
        Loop
        
        Encode = lrFin
    End Function
